.travis.yml

use this pr to test prow publish job

remove travis publish

---

build/copyright-check.sh
build/run-e2e-tests.sh
pkg/controller/propagator/policyMapper.go
pkg/controller/propagator/policy_propagator_controller.go
pkg/controller/propagator/propagation.go
test/e2e/case3_mutation_recovery_test.go
test/e2e/case4_unexpected_policy_test.go
test/resources/case4_unexpected_policy/case4-test-policy.yaml
test/resources/case4_unexpected_policy/case4-test-replicated-policy.yaml
test/utils/utils.go

This is an manual cherry-pick of #33
https://github.com/open-cluster-management/backlog/issues/10413

[release-2.1] Remove ownerReference and manually delete replicated 

---

pkg/controller/propagator/propagation.go

https://github.com/open-cluster-management/backlog/issues/10896

append placement to status when policy is disabled

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
Makefile
OWNERS
README.md
SECURITY.md

The README deployment/testing steps were updated to match the KinD tests in the Github Actions.

Use community templates

---

README.md

Rebuild due to the scan issue https://github.com/open-cluster-management/backlog/issues/13274

rebuild the image to get the new glib2 packages

---

pkg/controller/add_controllers.go
pkg/controller/policymetrics/metrics.go
pkg/controller/policymetrics/policymetrics_controller.go
pkg/controller/propagator/metric.go

Add copyright header

---

pkg/controller/add_controllers.go

add support for env variable to disable metrics

---

pkg/controller/policymetrics/metrics.go
pkg/controller/policymetrics/policymetrics_controller.go

rename metrics based on discussion w/ insights

---

README.md
test/e2e/case6_metrics_test.go

needed for https://github.com/open-cluster-management/backlog/issues/15238

change readme date to trigger rebuild

---

pkg/controller/propagator/propagation.go

Read each commit for more details.

Simplify some of the code in handleRootPolicy

---

cmd/manager/main.go
pkg/controller/propagator/placementDecisionMapper.go
pkg/controller/propagator/propagation.go
test/e2e/case6_placement_propagation_test.go
test/e2e/case7_bindings_test.go
test/utils/utils.go

Port review changes from community to this repo. https://github.com/open-cluster-management/backlog/issues/15604

updates from upstream review of placement changes

---

pkg/controller/propagator/propagation.go

Signed-off-by: ckandag <ckandaga@redhat.com>

Handle Template processing errors

---

controllers/propagator/propagation.go

Signed-off-by: ckandag <ckandaga@redhat.com>
https://github.com/open-cluster-management/backlog/issues/16674
Setting this annotation on the configuration policy template will prevent any template processing.
"policy.open-cluster-management.io/disable-templates" :  "true"

Add annotation to disable template processing

---

api/v1/policy_types.go
deploy/crds/policy.open-cluster-management.io_policies.yaml

https://github.com/open-cluster-management/backlog/issues/17098

Improve CRD validation to error on missing/misspelled fields (#17098)

---

api/v1/placementbinding_types.go
deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
test/e2e/case1_propagation_test.go
test/e2e/case6_placement_propagation_test.go

Related to https://github.com/open-cluster-management/backlog/issues/11709

Restrict APIGroup field of Subject and PlacementSubject

---

controllers/propagator/propagation.go

Previous to this commit, the policy template configuration was a package
variable but a recent change made template process happen concurrently.
This makes modifications to the template configuration susceptible to
race conditions. The race conditions aren't currently hit because the
only change that is made is the lookup namespace restriction, which is
different for each policy but not for each placement decision, which is
where the concurrency happens.
This will make future changes easier that involve policy template
configuration changes per placement decision.

Make the template config a local variable

---

go.mod
go.sum

Remove uneeded replace

---

api/v1/groupversion_info.go
api/v1/placementbinding_types.go
api/v1/policy_types.go
api/v1/policyset_types.go
controllers/common/common.go
controllers/propagator/placementBindingMapper.go
controllers/propagator/placementBindingPredicate.go
controllers/propagator/placementDecisionMapper.go
controllers/propagator/placementRuleMapper.go
controllers/propagator/policySetMapper.go
controllers/propagator/policySetPredicate.go
controllers/propagator/policy_controller.go
controllers/propagator/propagation.go
deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
deploy/crds/policy.open-cluster-management.io_policies.yaml
deploy/crds/policy.open-cluster-management.io_policysets.yaml
test/e2e/case10_policyset_propagation_test.go
test/e2e/e2e_suite_test.go
test/resources/case10_policyset_propagation/case10-test-policyset-policy.yaml
test/resources/case10_policyset_propagation/case10-test-policyset.yaml

https://github.com/stolostron/backlog/issues/18401
- Added watch on `PolicySet` resources and implemented a mapper
- Added `PolicySet` to pb.subject.kind enum list
- Added `PolicySet` support to existing mapper and predicate
- Added `PolicySet` field to status.placement

Support policy propagation through policyset

---

deploy/operator.yaml

Probably not a necessary change, but for consistency sake...

[release-2.3] Use `latest-2.3` image

---

controllers/propagator/policy_controller.go
test/e2e/case10_policyset_propagation_test.go
test/resources/case10_policyset_propagation/case10-test-multiple-policysets.yaml

stolostron/backlog#18401
Handle the case when a policy is removed from a policy set

Use standard `EnqueueRequestsFromMapFunc` for policySetMapper

---

Makefile
README.md
controllers/propagator/encryption.go
controllers/propagator/encryption_test.go
controllers/propagator/propagation.go
controllers/propagator/propagation_test.go
go.mod
go.sum
test/e2e/case9_templates_test.go
test/e2e/e2e_suite_test.go
test/resources/case9_templates/case9-test-encryption-secret.yaml
test/resources/case9_templates/case9-test-policy_encrypted.yaml
test/resources/case9_templates/case9-test-replpolicy_encrypted-managed1.yaml
test/resources/case9_templates/case9-test-replpolicy_encrypted-managed2.yaml

Addresses:
- https://github.com/stolostron/backlog/issues/18712
Has a dependency on:
- https://github.com/stolostron/go-template-utils/pull/32

Add logic for encrypted template functions

---

.github/workflows/kind.yml
.gitignore
Makefile
build/common/config/.golangci.yml
build/common/scripts/coverage_calc.sh
controllers/encryptionkeys/encryptionkeys_controller_test.go
controllers/propagator/encryption_test.go
controllers/suite_test.go
go.mod
go.sum
main_test.go
sonar-project.properties
test/e2e/case10_policyset_propagation_test.go
test/e2e/case11_policyset_controller_test.go
test/e2e/case12_encryptionkeys_controller_test.go
test/e2e/case1_propagation_test.go
test/e2e/case2_aggregation_test.go
test/e2e/case3_mutation_recovery_test.go
test/e2e/case4_unexpected_policy_test.go
test/e2e/case5_policy_automation_test.go
test/e2e/case6_placement_propagation_test.go
test/e2e/case7_bindings_test.go
test/e2e/case8_metrics_test.go
test/e2e/case9_templates_test.go
test/e2e/e2e_suite_test.go
test/utils/utils.go

Addresses:
- https://github.com/stolostron/backlog/issues/10735
Dependency on:
- https://github.com/openshift/release/pull/26112

Add SonarCloud to GitHub Actions

---

controllers/common/common.go
controllers/policyset/policyset_controller.go
controllers/propagator/propagation.go
test/e2e/case11_policyset_controller_test.go
test/resources/case11_policyset_controller/case11-plc-managed2.yaml
test/resources/case11_policyset_controller/case11-plcset-managed1.yaml
test/resources/case11_policyset_controller/case11-statuscheck-5.yaml

Fixes an issue where the policyset results field was not scoped to the policyset placement

Scope policyset results to placement

---

Makefile
controllers/common/common.go
controllers/policyset/placementDecisionMapper.go
controllers/policyset/policyset_controller.go
controllers/propagator/placementDecisionMapper.go
controllers/propagator/policy_controller.go
controllers/propagator/propagation.go
go.mod
go.sum
main.go
test/e2e/e2e_suite_test.go
test/utils/utils.go

https://github.com/stolostron/backlog/issues/19190

Upgrade placement API to v1beta1

---

controllers/policyset/policyset_controller.go

This matches how policy status is being updated by the controller. 
It improves the performance and scalability.

Use merge patch to update PolicySet status

---

README.md

No-op to regenerate prow job

---

controllers/common/common.go
controllers/propagator/policy_controller.go
controllers/propagator/propagation.go
controllers/propagator/propagation_test.go

https://github.com/stolostron/backlog/issues/20161

add concurrency to replicated policy deletion

---

controllers/policyset/policyset_controller.go

https://github.com/stolostron/backlog/issues/20446

generate event when policyset child plc is not found

---

controllers/policyset/policyset_controller.go
test/e2e/case11_policyset_controller_test.go
test/resources/case11_policyset_controller/case11-empty-plcset.yaml

https://github.com/stolostron/backlog/issues/20774

fix status in policysets with no policies

---

controllers/policyset/policyset_controller.go
test/e2e/case11_policyset_controller_test.go
test/resources/case11_policyset_controller/case11-compliant-plc.yaml
test/resources/case11_policyset_controller/case11-patch-plcset-2.yaml
test/resources/case11_policyset_controller/case11-statuscheck-5.yaml
test/resources/case11_policyset_controller/case11-statuscheck-6.yaml

https://github.com/stolostron/backlog/issues/20910

include compliance status when a plcset contains disabled policies

---

controllers/propagator/policyMapper.go
test/e2e/case4_unexpected_policy_test.go
test/resources/case4_unexpected_policy/case4-test-replicated-policy-out-of-cluster.yaml

ref: https://github.com/stolostron/backlog/issues/21032

Filter out non-cluster policies

---

README.md

Testing failures because the latest tagged image doesn't have the
latest code in it

No-op PR to re-push the latest image

---

README.md

No code changes just want a new build to resolve CVE found in installed
packages
Refs:
- https://github.com/stolostron/backlog/issues/22449

Force a new build to get updated packages

---

README.md

Not a code change, just refresh the build for a CVE
Refs:
- https://github.com/stolostron/backlog/issues/22449

Backport the build refresh

---

.github/workflows/framework-kind.yaml
Makefile

For https://github.com/stolostron/backlog/issues/21795.
Based off of https://github.com/stolostron/governance-policy-spec-sync/pull/118

Fw kind tests

---

README.md

This is to pick up updated packages -- no code
change
Refs:
- https://github.com/stolostron/backlog/issues/23975

Only changing the readme to force a new build

---

.github/workflows/kind.yml
CHANGELOG/CHANGELOG-v0.8.0.md
Makefile
build/common/config/.golangci.yml
controllers/common/ansible.go
controllers/policyset/policyset_controller.go
controllers/propagator/propagation.go

Closes https://github.com/stolostron/governance-policy-propagator/issues/218

Sync 1.18 changes

---

.github/workflows/framework-kind.yaml
.github/workflows/kind.yml
.github/workflows/upstream.yml

Relates:
https://github.com/stolostron/backlog/issues/24763

Use the go.mod file for the Go version in CI

---

.ci-operator.yaml
build/Dockerfile

- https://github.com/stolostron/backlog/issues/24860

Add in-repo Prow config

---

controllers/automation/policyautomation_controller.go
test/e2e/case5_policy_automation_test.go

This automates cleaning up PolicyAutomation objects when the associated
Policy object is deleted.
Relates:
https://github.com/stolostron/backlog/issues/24943
(cherry picked from commit 0eda8cded038e25d75c3a8f51c18f649ff6c3bae)
This is a cherry-pick of #235.

[release-2.5] Set the owner reference on PolicyAutomation objects

---

.github/workflows/framework-kind.yaml

Refs:
- https://github.com/stolostron/backlog/issues/22914

Use reusable workflow for framework tests

---

README.md

Trigger a new build to refresh images.
Refs:
- https://github.com/stolostron/backlog/issues/25750

This change is only triggering a new build

---

README.md

Retry prow image build with new pr
Refs:
- https://coreos.slack.com/archives/C02UXRV7QP8/p1663222190238259

Prow image failures happened a lot yesterday

---

.github/workflows/kind.yml
Makefile

Sync from upstream:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/72

Manual upstream sync - Set "minimum" tag in Makefile

---

Makefile
deploy/crds/kustomize/kustomization.yaml
deploy/crds/kustomize/ns-validation.json
deploy/crds/kustomize/policy.open-cluster-management.io_policies.yaml
test/e2e/case15_dep_crd_validation_test.go
test/resources/case15_dep_crd_validation/basic-policy.yaml

Sync upstream PR:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/73
Closes #291

Manual upstream sync - Add CRD validation for namespaces in dependencies

---

.ci-operator.yaml
api/v1/groupversion_info.go
api/v1beta1/groupversion_info.go
build/Dockerfile
build/common/config/.golangci.yml
controllers/propagator/propagation.go
go.mod
test/utils/utils.go

ref: https://github.com/stolostron/backlog/issues/27048
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>

[release-2.5] Upgrade to Go 1.19

---

build/Dockerfile

Manual sync of:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/77
Closes #298

[upstream-sync] Clean up extra lines in Dockerfile

---

.github/workflows/kind.yml
controllers/propagator/propagation.go
go.mod
go.sum
test/e2e/case14_root_policy_metrics_test.go
test/e2e/case9_templates_test.go
test/resources/case9_templates/case9-test-policy.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1-relabelled.yaml
test/resources/case9_templates/case9-test-replpolicy-managed2.yaml

The commits applied cleanly for me...
* open-cluster-management-io/governance-policy-propagator#95
Closes #351

Sync from open-cluster-management-io/governance-policy-propagator: #95

---

.github/workflows/framework-kind.yaml

Refs:
- https://issues.redhat.com/browse/ACM-5759

[release-2.6] Pin the framework workflow to release-2.6

---

controllers/common/ansible.go
test/e2e/case5_policy_automation_test.go
test/resources/case5_policy_automation/case5-policy-automation-disable.yaml
test/resources/case5_policy_automation/case5-policy-automation-everyEvent.yaml

This is not an automated cherry-pick of #375
For https://issues.redhat.com/browse/ACM-5311

[release-2.6] 🥸 Sync from open-cluster-management-io/governance-policy-propagator: #107

---

controllers/propagator/propagation.go
go.mod
go.sum
test/e2e/case9_templates_test.go
test/resources/case9_templates/case9-test-policy-cslookup.yaml
test/resources/case9_templates/case9-test-policy.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1-relabelled.yaml
test/resources/case9_templates/case9-test-replpolicy-managed1.yaml
test/resources/case9_templates/case9-test-replpolicy-managed2.yaml

Sync:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/115
(cherry picked from commit 80bd4030d5de9a1921dda3ba1b391eb6ea9c2395)
Closes #399

Manual Sync: Better handling of cluster-scoped template lookups

---

.github/workflows/kind.yml

Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
(cherry picked from commit be8b19e3c53ee5f9cddc64665098158618680bb0)
Cherry-pick:
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/147
Closes #499

Manual sync - Add generated code check

---

.github/workflows/kind.yml
Makefile
build/common/Makefile.common.mk

[Manual Sync] Syncing #146

---

controllers/propagator/replicatedpolicy_controller.go

ref: https://issues.redhat.com/browse/ACM-9461
Signed-off-by: Dale Haiducek <19750917+dhaiducek@users.noreply.github.com>
(cherry picked from commit c3c38e19a25d98abf40bcb92566a881c3dc377fd)
Cherry-pick commit from:
- #551 
- open-cluster-management-io/governance-policy-propagator#168

[release-2.9] Manual cherry-pick (Add back propagation/update events)

---

.github/workflows/kind.yml
build/common/Makefile.common.mk

Manual sync:
* open-cluster-management-io/governance-policy-propagator#183
* open-cluster-management-io/governance-policy-propagator#184
Closes #572

Manual sync: Sync Makefile; Simplify actions

---

.github/workflows/kind.yml
Makefile
controllers/complianceeventsapi/auth.go
controllers/complianceeventsapi/server.go
go.mod
go.sum
test/e2e/case18_compliance_api_test.go
test/e2e/case19_rep_policy_placement_test.go
test/e2e/case20_compliance_api_controller_test.go
test/resources/case18_compliance_api_test/subset_service_account.yaml
test/resources/case18_compliance_api_test/wrong_service_account.yaml
test/resources/managed4-cluster.yaml
test/resources/managed5-cluster.yaml
test/resources/managed6-cluster.yaml

Closes #578 
The conflict was in go.sum.

Manual sync of upstream PR #164

---

go.mod
go.sum
test/resources/case18_compliance_api_test/wrong_service_account.yaml

Manual sync of upstream PR #199

---

controllers/complianceeventsapi/server.go
go.mod
go.sum
test/e2e/case18_compliance_api_test.go

Manual sync of the upstream PR: #214

---

.tekton/governance-policy-propagator-acm-210-pull-request.yaml
.tekton/governance-policy-propagator-acm-210-push.yaml
build/Dockerfile
build/Dockerfile.rhtap

Also updates ubi8 --> ubi9
Contains changes from:
- #715 
ref: https://issues.redhat.com/browse/ACM-10739

[release-2.10] Use entitled Dockerfile for Konflux

---

go.mod
go.sum

[Manual Sync] Update kubernetes-dependency-watches to v0.7.0

---

.tekton/governance-policy-propagator-acm-211-pull-request.yaml
.tekton/governance-policy-propagator-acm-211-push.yaml

This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263

fix(KONFLUX-3663): format PipelineRun files and upload SAST results

---

.ci-operator.yaml
Makefile
build/Dockerfile
build/Dockerfile.rhtap
go.mod

ref: https://issues.redhat.com/browse/ACM-14251

Update to Go v1.22

---

.ci-operator.yaml
Makefile
build/Dockerfile
build/Dockerfile.rhtap
go.mod

ref: https://issues.redhat.com/browse/ACM-14251

[release-2.11] Update to Go v1.22

---

.tekton/governance-policy-propagator-acm-214-push.yaml

Refs:
- https://issues.redhat.com/browse/ACM-20948

Add multiarch build to konflux pipeline
