stolostron/governance-policy-propagator

- deploy/crds/policy.open-cluster-management.io_policies_crd.yaml
- pkg/apis/policy/v1/policy_types.go
https://github.com/open-cluster-management/backlog/issues/3318
```
ycao@MacBook-Pro governance-policy-propagator % kubectl get policy -A     
I0421 10:49:37.630466   92294 request.go:645] Throttling request took 1.147729156s, request: GET:https://api.policy-grc-cp-autoclaims-cjcz2.dev08.red-chesterfield.com:6443/apis/webhook.certmanager.k8s.io/v1beta1?timeout=32s
NAMESPACE       NAME                                          REMEDIATION ACTION   COMPLIANCE STATE   AGE
default         policy-install-acs-central                    enforce              Compliant          149m
default         policy-install-acs-cluster-services           enforce              Compliant          19m
default         test-pod-policy-dhaiduce                      enforce              Compliant          40m
gparvin …
```
> print additional columns for policy

- pkg/controller/propagator/propagation.go
Make sure the owner reference for the managed cluster hub policies is the parent policy -- not the owner reference in the parent policy which can be anything.
**Update** Using the parent policy just would not work for some reason -- instead clearing the OwnerReference has fixed the problem that I'm seeing.  Note that the problem can be recreated by:
1. Clone repo `git@github.com:rcarrillocruz/cluster-group-lcm.git`
2. Run `make install run`
3. Create the `Group` resource from the group.yaml but make sure you update the managed cluster reference from `spoke1` and `spoke2` to something you have.
This causes a policy to be created with the operator or group as the owner and we currently do a DeepCopy which keeps that owner reference.  This …
> set the mc policy owner reference to the parent policy

- pkg/controller/add_controllers.go
- pkg/controller/policymetrics/metrics.go
- pkg/controller/policymetrics/policymetrics_controller.go
Design doc: https://docs.google.com/document/d/1num_lVbdBv_rwz8CRD0WSIzjEZQwg6Fvre2Q3mKkOY4/edit?usp=sharing
Previous prototype: https://github.com/JustinKuli/governance-policy-metrics
This PR brings in the work from the prototype, adjusted to fit into the current system the propagator uses for managing the controllers. I think it's good to have the metrics piece as a separate controller, since the propagator currently only reconciles the root policies (changes to propagated policies will trigger a root policy update through the predicate). The metrics needs to have information on the propagated policies.
This PR will need to be followed up by an update to the GRC chart to add a service monitor so these metrics are collected by prometheus.
When a policy is compliant, its status metric …
> Add policy compliance metrics

- pkg/controller/propagator/propagation.go
fix a bug of copying finalizers from user namespace to clusters namespaces.
finalizer has to be removed to avoid having the policy stuck forever on the MCs.
Signed-off-by: Nir Rozenbaum <nirro@il.ibm.com>
> bug fix - do not copy finalizers from user namespace to MC namespaces

- cmd/manager/main.go
Previous testing had shown that the new values for QPS and Burst (200.0
and 400, respectively) work better for us than the controller-runtime
defaults. However, further tuning may be needed in the future. These
environment variables, as well as the (now) exposed
ocm_handle_root_policy_duration_seconds metric should help in that
process.
Refs:
- https://github.com/open-cluster-management/backlog/issues/14583
> Add env vars for controller QPS and Burst tuning

- test/e2e/case6_metrics_test.go
- test/resources/case6_metrics/case6-test-policy.yaml
- test/resources/case6_metrics/managed-both-status-compliant.yaml
- test/resources/case6_metrics/managed-both-status-noncompliant.yaml
- test/utils/utils.go
Because the endpoint isn't directly exposed, it would take some extra
work to get it to a "regular" endpoint that the tests could connect to.
So, instead, this exec's into the pod, where it *can* curl the metrics
endpoint directly. The new util function could be useful for testing
other metrics in the future.
Refs:
- https://github.com/open-cluster-management/backlog/issues/14992
> Add tests for the policy info metrics

- test/e2e/case8_metrics_test.go
- test/resources/case8_metrics/case8-test-policy.yaml
- test/resources/case8_metrics/managed-both-status-compliant.yaml
- test/resources/case8_metrics/managed-both-status-noncompliant.yaml
The metrics tests will now be case 8.
https://github.com/open-cluster-management/governance-policy-propagator/pull/83 and https://github.com/open-cluster-management/governance-policy-propagator/pull/81 collided, both defined case6 for their tests.
> Fix name collision (case6) on tests

- pkg/controller/propagator/policy_propagator_controller.go
- pkg/controller/propagator/propagation.go
- pkg/controller/propagator/propagation_test.go
Rather than give up entirely on a reconcile request even after retries are exhausted in the handleRootPolicy method, this requeues the request to be processed 5 minutes later instead.
> Requeue requests with a delay after failed retries

- pkg/controller/propagator/propagation.go
The errors are ignored on purpose and thus they are false positives
detected by sonarcloud. They should just be ignored.
Here is an example of the failed sonarcloud run:
https://sonarcloud.io/project/issues?branch=release-2.4&id=open-cluster-management_governance-policy-propagator&resolved=false&types=VULNERABILITY
> Ignore false positives for gosec:G104

- deploy/operator.yaml
- test/resources/case9_templates/case9-test-policy.yaml
- test/resources/case9_templates/case9-test-replpolicy-managed1.yaml
- test/resources/case9_templates/case9-test-replpolicy-managed2.yaml
This is testing functionality added in:
https://github.com/open-cluster-management/governance-policy-propagator/commit/d0d1645714ebc3e5a198b431eed5a8f8ba3ea12d
The first commit grants the service account read access to everything to match the GRC helm chart configuration. This is required for testing hub side templates which lookup secrets.
> Add E2E tests for hub side template indentation

- controllers/propagator/propagation.go
- go.mod
- go.sum
This fixes a regression as described in:
https://github.com/open-cluster-management/go-template-utils/pull/19
Because of this, the additional indentation also had to be adjusted to
account for this.
> Update go-template-utils to v1.2.3

- api/v1/placementbinding_types.go
- deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
- test/e2e/case1_propagation_test.go
- test/e2e/case6_placement_propagation_test.go
The propagator only handles first matching subject in placementbinding.
See https://tinyurl.com/yrtd6e4r. Add this restriction to CRD.
> Restrict length of pb.spec.subjects to 1 

- .github/workflows/kind.yml
- build/Dockerfile
- go.mod
Go builds downstream have moved to go 1.17.  Moving build to match.
> Use go 1.17 to match downstream go version

- controllers/automation/policyautomation_controller.go
- controllers/policymetrics/policymetrics_controller.go
- controllers/propagator/placementBindingMapper.go
- controllers/propagator/placementDecisionMapper.go
- controllers/propagator/placementRuleMapper.go
- controllers/propagator/policyMapper.go
- controllers/propagator/policy_controller.go
- controllers/propagator/propagation.go
- main.go
This converts all logging to use the zap logging library. It also
refactors the existing log messages to be structured and have different
verbosity. The messages were also changed to have a more consistent
style. Lastly, log messages are added in places where they were
missing.
Resolves:
https://github.com/open-cluster-management/backlog/issues/18025
> Refactor and add additional logging

- controllers/propagator/encryption.go
- controllers/propagator/encryption_test.go
- controllers/propagator/policy_controller.go
- controllers/propagator/propagation.go
If a policy has Hub policy templates, an AES-256 key will be generated
for each managed cluster that the policy targets. The key is stored in
the `policy-encryption-key` secret in the managed cluster namespace.
Resolves:
https://github.com/stolostron/backlog/issues/18706
> Generate encryption keys for each managed cluster

- Makefile
The build target called the fmt target which downloaded formatting
tools. This caused offline builds to fail.
Resolves:
https://github.com/stolostron/backlog/issues/19094
> Allow offline builds

- api/v1/placementbinding_types.go
- deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
This reverts chnage in commit b7fd147
which restricts subjects to max 1 as it breaks the use case where one
placementbinding is used to binding multiple policies.
> pb.subjects shouldn't be limited to 1

- api/v1/groupversion_info.go
- api/v1/placementbinding_types.go
- api/v1/policy_types.go
- api/v1/policyset_types.go
- controllers/common/common.go
- controllers/propagator/placementBindingMapper.go
- controllers/propagator/placementBindingPredicate.go
- controllers/propagator/placementDecisionMapper.go
- controllers/propagator/placementRuleMapper.go
- controllers/propagator/policySetMapper.go
- controllers/propagator/policySetPredicate.go
- controllers/propagator/policy_controller.go
- controllers/propagator/propagation.go
- deploy/crds/policy.open-cluster-management.io_placementbindings.yaml
- deploy/crds/policy.open-cluster-management.io_policies.yaml
- deploy/crds/policy.open-cluster-management.io_policysets.yaml
- test/e2e/case10_policyset_propagation_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case10_policyset_propagation/case10-test-policyset-placement.yaml
- test/resources/case10_policyset_propagation/case10-test-policyset-policy-placement.yaml
- test/resources/case10_policyset_propagation/case10-test-policyset-policy.yaml
- test/resources/case10_policyset_propagation/case10-test-policyset.yaml
stolostron/backlog#18401
- Added watch on `PolicySet` resources
- Implemented a mapper and predicate for `PolicySet` watch
- Added `PolicySet` to pb.subject.kind enum list
- Added `PolicySet` support to existing mapper and predicate
- Added `PolicySet` field to status.placement
> Support policy propagation through policyset

- controllers/propagator/placementBindingMapper.go
- controllers/propagator/placementDecisionMapper.go
- controllers/propagator/placementRuleMapper.go
- test/e2e/case10_policyset_propagation_test.go
- test/resources/case10_policyset_propagation/case10-test-multiple-policysets-single-pb.yaml
When a placementbinding references multiple subjects, the mapper should 
always loop through entire subjects to generate reconcile request even when a 
policyset couldn't be retrieved.
> Ensure reconcile requests are generated correctly

- controllers/common/common.go
- controllers/encryptionkeys/encryptionkeys_controller.go
- controllers/encryptionkeys/encryptionkeys_controller_test.go
- controllers/propagator/encryption.go
- controllers/propagator/encryption_test.go
- controllers/propagator/policy_controller.go
- controllers/propagator/propagation.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
- main.go
- test/e2e/case12_encryptionkeys_controller_test.go
- test/resources/case9_templates/case9-test-encryption-secret.yaml
This controller is responsible for rotating encryption keys in the
policy-encryption-key secrets for each managed cluster.
This adds a watch to such secrets, which inherently caches these values
so the custom encryption key cache for the main controller was removed.
Resolves:
https://github.com/stolostron/backlog/issues/18723
> Add the policy-encryption-keys controller

- controllers/propagator/propagation.go
- test/e2e/case10_policyset_propagation_test.go
- test/resources/case10_policyset_propagation/case10-test-multiple-policies-policysets-single-pb.yaml
https://github.com/stolostron/backlog/issues/19711
When a placement binding contains multiple policysets in the subjects,
the propagator appends the first subject as the placement. This is not
correct as the policyset may not even contain the policy. Need to get
the policyset and loop through the policies in it to determine and only
append when there is a match.
> Generate placement for every policyset in pb.subjects

- controllers/propagator/propagation.go
If a policy using encryption was created without any annotations (which
is tricky to do - kubectl automatically adds some), then the propagator
will panic when trying to write the initialization vector to the nil
map.
> Fix panic on nil annotations

- Makefile
- go.mod
- go.sum
- main.go
- test/e2e/e2e_suite_test.go
This will make the logs look more consistent, and allow for better run-
time configuration of both logs this controller creates, and the logs
that libraries might create.
> Configure logging with utility package

- build/Dockerfile
- build/template-delimiter.patch
- deploy/crds/external/tower.ansible.com_joblaunch_crd.yaml
This backports the upstream fix to the text/template library. This is
required so that fields that start with the letter `h` can be accessed
within Hub policy templates.
The second commit fixes the E2E test.
Relates:
https://github.com/stolostron/backlog/issues/21440
> Fix text/template so that it doesn't confuse the action for a delimiter

- Makefile
- api/v1beta1/policyset_types.go
- controllers/policyset/policyset_controller.go
- deploy/crds/policy.open-cluster-management.io_policysets.yaml
- test/e2e/case11_policyset_controller_test.go
- test/resources/case11_policyset_controller/case11-plcset-multistatus.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-1.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-2.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-3.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-4.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-5.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-6.yaml
- test/resources/case11_policyset_controller/case11-statuscheck-7.yaml
The PolicySet status sometimes shows the compliance status and
sometimes it doesn't.  To help understand what's going on we need a
message.  In the future we may have a pending state for policies, but
for now we just want a message in the PolicySet to explain whether the
status is unable to account for some of the policies.
Refs:
- https://github.com/stolostron/backlog/issues/21750
> Add a statusMessage to the PolicySet status

- .github/workflows/kind.yml
The `v1beta1` CRD is removed in `v1.22`, so the ManagedCluster will fail to deploy.
> [release-2.3] Set Kind version

- test/crds/cluster.open-cluster-management.io_managedclusters.yaml
This ManagedCluster CRD matches the version in use in `go.mod` for `open-cluster-management.io/api`.
> Align ManagedCluster CRD; Update APIVersion

- .github/workflows/kind.yml
- Makefile
This way we won't get hit by breaking updates to the `main` branch upstream.
> Use `api` tag from `go.mod`

- controllers/common/common.go
- controllers/common/common_test.go
- controllers/encryptionkeys/encryptionkeys_controller.go
- controllers/policyset/policyset_controller.go
- controllers/propagator/policyMapper.go
- controllers/propagator/propagation.go
There were two places where the root-policy label was assumed to have one `.` in it, since that's how the propagator sets the label. But if a user created a Policy with that label, it doesn't necessarily have that character, so the propagator could panic trying to access a value out of the range of the slice.
There was another spot that used a similar split, but that one is safe, for now.
Refs:
- https://github.com/stolostron/backlog/issues/26592
(cherry picked from commit 2914c006d17e26c46cbaf42f74585971f58a5554)
> [release-2.5] Prevent panic from unexpected label values

- controllers/common/common.go
- controllers/common/common_test.go
- controllers/encryptionkeys/encryptionkeys_controller.go
- controllers/policyset/policyset_controller.go
- controllers/propagator/policyMapper.go
- controllers/propagator/propagation.go
There were two places where the root-policy label was assumed to have one `.` in it, since that's how the propagator sets the label. But if a user created a Policy with that label, it doesn't necessarily have that character, so the propagator could panic trying to access a value out of the range of the slice.
There was another spot that used a similar split, but that one is safe, for now.
Refs:
- https://github.com/stolostron/backlog/issues/26592
(cherry picked from commit 2914c006d17e26c46cbaf42f74585971f58a5554)
> [release-2.6] Prevent panic from unexpected label values

- controllers/common/common.go
- controllers/common/common_test.go
- controllers/propagator/policyMapper.go
This is a backport of 2914c006d17e26c46cbaf42f74585971f58a5554. The root policy label can not be assumed to have exactly 1 `.`, and in the case where that character wasn't present at all, the controller would panic and crash.
Refs:
- https://github.com/stolostron/backlog/issues/26592
> [release-2.4] Prevent panic from unexpected label values

- controllers/propagator/policy_controller.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
Leader Election, for which  ConfigMaps was needed, has since been removed
related to : https://github.com/stolostron/backlog/issues/26574
Signed-off-by: Chaitanya Kandagatla <ckandaga@redhat.com>
> Remove permissions not needed

- go.mod
- go.sum
Closes https://github.com/stolostron/governance-policy-propagator/issues/302
Relates:
https://issues.redhat.com/browse/ACM-2449
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
(cherry picked from commit 5f6402dedafafa32cd20fc6f97d7d72758bd80d6)
> [Upstream Sync] Update kubernetes-dependency-watches to v0.1.1

- Makefile
- controllers/automation/policyPredicate.go
- controllers/automation/policyautomation_controller.go
- controllers/common/ansible.go
- go.mod
- test/e2e/case5_policy_automation_test.go
- test/resources/managed3-cluster.yaml
Cherrypick from upstream https://github.com/open-cluster-management-io/governance-policy-propagator/commit/21cd26d50a8e486a1ba1a6718872ab608ecedb1d
resolve issue #385 
Create a policy with disabled set to true. Then, create a policyAutomation with "everyevent" mode and "policyViolationLimits" set to 0.
Actual results:
Only the violaition status of one cluster was passed into the ansiblejob
Expected results:
All violations status of all clusters should be passed
Ref: https://issues.redhat.com/browse/ACM-4777
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
(cherry picked from commit 21cd26d50a8e486a1ba1a6718872ab608ecedb1d)
> Bug: Only one policyviolation when policyViolationLimit=0

- Makefile
- controllers/propagator/propagation.go
- deploy/manager/manager.yaml
- deploy/operator.yaml
- test/e2e/case6_placement_propagation_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case6_placement_propagation/extra-cluster.yaml
Previously, in certain error cases, the cluster would be marked as non- compliant, but the replicated policy would never be created. Now, these errors result in the root policy bein properly requeued, with an error listing which clusters failed.
Refs:
- https://issues.redhat.com/browse/ACM-4606
(cherry picked from commit a6681963700046812607ffab860099fde6c00b90)
For https://issues.redhat.com/browse/ACM-4710
Also for https://issues.redhat.com/browse/ACM-5310
> [release-2.6] Requeue root policy when some clusters fail

- Makefile
- controllers/automation/policyPredicate.go
- controllers/automation/policyautomation_controller.go
- controllers/common/ansible.go
- test/e2e/case5_policy_automation_test.go
- test/resources/managed3-cluster.yaml
Backport [release-2.7]
Create a policy with disabled set to true. Then, create a policyAutomation with "everyevent" mode and "policyViolationLimits" set to 0.
Actual results:
Only the violaition status of one cluster was passed into the ansiblejob
Expected results:
All violations status of all clusters should be passed
Ref: https://issues.redhat.com/browse/ACM-4777
> [release-2.7]Bug: Only one policyviolation when policyViolationLimit=0

- .github/workflows/kind.yml
- Makefile
- PROJECT
- README.md
- api/v1/policy_webhook.go
- deploy/manager/manager.yaml
- deploy/operator.yaml
- deploy/webhook.yaml
- main.go
- main_test.go
- test/e2e/case17_policy_webhook_test.go
- test/resources/case17_policy_webhook/case17_policy_long.yaml
- test/resources/case17_policy_webhook/case17_policy_replicate.yaml
The 63-character limit validation for policy name is not working while creating a Policy via CLI.
Policy creation - Policy name + namespace name can’t go longer than 63 From CLI, it possible to create a policy with a name like “policy-check-setupjob-setupjob-operator-installer” with no issue; but, while wanting to edit it, we can’t.
Getting this error: “The combined length of namespace and policy name (namespaceName.policyName) should not exceed 63 characters (see attached screenshot)
Ref: https://issues.redhat.com/browse/ACM-3558
- Resolve `makefile` conflict issue
Signed-off-by: Yi Rae Kim [yikim@redhat.com](mailto:yikim@redhat.com)
(cherry-picked from commit c93f938892c18f3fe84655246ee1a92a963ad62e)
> Manual cherry-pick Add webhook for limit 64 char name+np

- controllers/propagator/encryption.go
- controllers/propagator/encryption_test.go
- controllers/propagator/propagation.go
- controllers/propagator/replicatedpolicy_controller.go
- controllers/propagator/replicatedpolicy_setup.go
- go.mod
- go.sum
- main.go
Closes https://github.com/stolostron/governance-policy-propagator/issues/463
The conflict was in go.sum
> Manual Sync of #137

- .tekton/governance-policy-propagator-fm3n-pull-request.yaml
- .tekton/governance-policy-propagator-fm3n-push.yaml
- Dockerfile.rhtap
See the details in the associated task.
Refs:
- https://issues.redhat.com/browse/ACM-7178
> Add rhtap dockerfile with allowed image references

- .github/workflows/kind.yml
- Makefile
- test/e2e/case5_policy_automation_test.go
The PolicyAutomation tests were taking about half of the total e2e test duration. This excludes those tests from the usual `make e2e-test` target, which will accelerate both the CI and local development. Those tests are now run in a separate (concurrent) GH job in the CI workflow, and the test coverage information is merged in another new job.
This also combines the unit tests and linting tasks into one job, which means that a linting or formatting error will not prevent the e2e tests from running.
Refs:
- https://issues.redhat.com/browse/ACM-8239
(cherry picked from commit db0c8dd8f82fa9973c19b643d9fd1b41be86e1eb)
Closes https://github.com/stolostron/governance-policy-propagator/issues/488
> Run PolicyAutomation tests separately in CI

- .github/workflows/kind.yml
- Makefile
- deploy/manager/kustomization.yaml
- deploy/manager/manager.yaml
- deploy/manager/service-account.yaml
- test/e2e/case10_policyset_propagation_test.go
- test/e2e/case11_policyset_controller_test.go
- test/e2e/case12_encryptionkeys_controller_test.go
- test/e2e/case13_policyset_dependencies_test.go
- test/e2e/case14_root_policy_metrics_test.go
- test/e2e/case16_selective_policy_enforcement_test.go
- test/e2e/case17_policy_webhook_test.go
- test/e2e/case19_rep_policy_placement_test.go
- test/e2e/case1_propagation_test.go
- test/e2e/case2_aggregation_test.go
- test/e2e/case3_mutation_recovery_test.go
- test/e2e/case4_unexpected_policy_test.go
- test/e2e/case5_policy_automation_test.go
- test/e2e/case6_placement_propagation_test.go
- test/e2e/case7_bindings_test.go
- test/e2e/case8_metrics_test.go
- test/e2e/case9_templates_test.go
- test/e2e/e2e_suite_test.go
- test/resources/e2e_controller_secret.yaml
> [Manual Sync] Syncing #151

- controllers/propagator/propagation.go
- go.mod
- go.sum
This fixes the case where multiple managed clusters with the same policy with a hub template don't get updated when the referenced object in the hub template is changed.
This additionally handles clean up properly when template resolution fails.
Relates:
https://issues.redhat.com/browse/ACM-8928
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
(cherry picked from commit f81d2267e2794bcd8240e358176bad7433d80748)
> [Manual Sync] Fix hub template watches

- controllers/common/common.go
- controllers/common/common_status_update.go
- test/e2e/case2_aggregation_test.go
- test/resources/case2_aggregation/faulty-placementbinding.yaml
Manual cherry-pick from:
- #566 
With a PlacementBinding containing an invalid placementRef, the propagator was returning an error and endlessly re-reconciling. This occurs even if the PlacementBinding was not bound to the Policy.
Also swaps the namespace and name in the message because it was non-standard.
ref: https://issues.redhat.com/browse/ACM-9930
> [release-2.9] Manual cherry-pick: Fix status update with faulty PlacementBinding

- go.mod
- go.sum
Relates:
https://issues.redhat.com/browse/ACM-10833
This is the upstream related one:
https://github.com/open-cluster-management-io/governance-policy-propagator/pull/212
> [2.9] Update go-template-utils

- .github/workflows/kind.yml
- Makefile
- controllers/policyset/policyset_controller.go
- controllers/propagator/replicatedpolicy_setup.go
- controllers/rootpolicystatus/root_policy_status_controller.go
- main.go
- test/e2e/case4_unexpected_policy_test.go
Syncing the following PRs:
* open-cluster-management-io/governance-policy-propagator#232
(The PR included a change to a workflow which the app did not have permission to push.)
```
Add flag to disable PlacementRule watches
Some deployments will not want to install the PlacementRule CRD, since
it is an older API which may eventually be removed. This adds an
argument to the propagator which will disable all watches on
PlacementRules, allowing the controllers to run in those environments.
In addition, if the flag is not set, the controller will check for the
PlacementRule CRD on the cluster, and if not found, disable those
watches (which would otherwise fail and prevent the controller from
working).
Refs:
- https://issues.redhat.com/browse/ACM-2609
Signed-off-by: Justin Kulikauskas …
```
> 🙃 Sync from open-cluster-management-io/governance-policy-propagator: #231

- go.mod
- go.sum
> [Manual Sync] Update go-template-utils to v6.1.1

- .tekton/governance-policy-propagator-acm-210-pull-request.yaml
- .tekton/governance-policy-propagator-acm-210-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

- .github/workflows/kind.yml
- api/v1/policy_webhook.go
- Fix usage of deprecated webhook.Validator interface
- Set Go version for coverage to latest
Manual cherrypick
- https://github.com/open-cluster-management-io/governance-policy-propagator/pull/250
Closes #995
> Issue 995 - deprecated webhook.Validator
